name: check-if-pr-merged
description: Check if a pull request has been merged or direct pushes have been made to the main branch.

outputs:
  is-merged:
    description: 'Indicates whether the pull request has been merged or if direct pushes have been made to the main branch.'
    value: ${{ steps.check-pr.outputs.is-merged }}

runs:
  using: "composite"
  steps:
    - name: Check if pull request is merged or direct push to main
      id: check-pr
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "is-merged=false" >> $GITHUB_OUTPUT
        else
          PR_LIST=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls)
          PR_COUNT=$(echo "$PR_LIST" | jq length)
          if [ "$PR_COUNT" -gt 0 ]; then
            echo "is-merged=true" >> $GITHUB_OUTPUT
          else
            echo "is-merged=false" >> $GITHUB_OUTPUT
          fi
        fi