name: Checkov Plan Scan
description: Run a Checkov scan on Terraform plan files.

inputs:
  tf_directory:
    description: 'The directory containing the Terraform files to scan.'
    required: true
    default: './'
  checkov_soft_fail:
    description: 'If true, the Checkov scan will not fail the workflow issues.'
    required: true
    default: 'false'


runs:
  using: "composite"
  steps:
    - name: change tfplan to json
      shell: bash
      working-directory: ${{ inputs.tf_directory }}
      run: terraform show -json tfplan.binary > tfplan.json
    - name: Checkov Plan Scan
      uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7
      with:
        file: ${{ inputs.tf_directory }}/tfplan.json
        soft_fail: ${{ inputs.checkov_soft_fail }}
        skip_check: CKV2_AWS_5, CKV2_AWS_11, CKV2_AWS_34, CKV2_AWS_19, CKV_AWS_39, CKV_AWS_133, CKV_AWS_157, CKV_AWS_161, CKV_AWS_293, CKV_AWS_382, CKV_AWS_339, CKV_AWS_38, CKV_AWS_338, CKV_AWS_158, CKV_AWS_341, CKV_AWS_355, CKV_AWS_290
        output_format: cli,sarif
        output_file_path: console,results.sarif
    - name: Upload Checkov SARIF Results
      uses: github/codeql-action/upload-sarif@18420e3271f74589575af831a523c833acda327f
      with:
        sarif_file: ${{ github.workspace }}/results.sarif
