name: Terraform Scan and Apply

on:
  pull_request: 
    paths-ignore: 
      - ".github/workflows/**"
      
  push: 
    branches:
      - main
    paths-ignore: 
      - ".github/workflows/**"

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  TF_DIR: "vpc eks rds addons"
  CHECKOV_SOFT_FAIL: false




permissions:
  contents: read
  id-token: write
  security-events: write
  pull-requests: write

jobs:
  detect-which-dirs-changed:
    runs-on: ubuntu-24.04
    outputs:
      vpc: ${{ steps.filter.outputs.vpc }}
      eks: ${{ steps.filter.outputs.eks }}
      rds: ${{ steps.filter.outputs.rds }}
      addons: ${{ steps.filter.outputs.addons }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Filter changed directories
        id: filter
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
        with:
          filters: |
            vpc: 'vpc/**'
            eks: 'eks/**'
            rds: 'rds/**'
            addons: 'addons/**'


  terraform-static-scan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: set up Terraform, cache providers
        uses: ./.github/workflows/terraform-setup-cache
        with:
          tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }}
          terraform_version: 1.15.8

      - name: Terraform Init and Validate
        uses: ./.github/workflows/terraform-static-scan
        with:
          tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }}
          tf_dirs: ${{ env.TF_DIR }}
          checkov_soft_fail: ${{ env.CHECKOV_SOFT_FAIL }}
      


  vpc:
    needs: detect-which-dirs-changed
    environment: dev
    if: needs.detect-which-dirs-changed.outputs.vpc == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: set up Terraform, cache providers, and configure AWS credentials
        uses: ./.github/workflows/terraform-aws-init
        with:
          tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }}
          terraform_version: 1.15.8
          aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
          aws_region: us-east-1
          backend_bucket: ${{ vars.BACKEND_BUCKET }}
          backend_key: ${{ vars.VPC_BACKEND_KEY }}
          working_directory: vpc
      - name: Terraform Plan
        working-directory: vpc
        shell: bash
        run: |
          terraform plan -out=tfplan.binary -var-file=./environment/dev.tfvars -input=false
          terraform show -no-color tfplan.binary > tfplan.txt
      - name: checkov plan scan
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/checkov-plan-scan
        with:
          tf_directory: vpc
          checkov_soft_fail: ${{ env.CHECKOV_SOFT_FAIL }}
      - name: comment plan on pr
        if: github.event_name == 'pull_request'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('vpc/tfplan.txt', 'utf8');
            const commentBody = `### Terraform Plan for VPC\n\`\`\`\n${plan}\n\`\`\``;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: vpc
        shell: bash
        run: terraform apply -auto-approve tfplan.binary
  eks:
    needs: [detect-which-dirs-changed, vpc] 
    environment: dev
    if: always() && needs.detect-which-dirs-changed.outputs.eks == 'true' && (needs.vpc.result == 'success' || needs.vpc.result == 'skipped')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: set up Terraform, cache providers, and configure AWS credentials
        uses: ./.github/workflows/terraform-aws-init
        with:
          tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }}
          terraform_version: 1.15.8
          aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
          aws_region: us-east-1
          backend_bucket: ${{ vars.BACKEND_BUCKET }}
          backend_key: ${{ vars.EKS_BACKEND_KEY }}
          working_directory: eks
      - name: Terraform Plan
        working-directory: eks
        shell: bash
        run: |
          terraform plan -out=tfplan.binary -var-file=./environment/dev.tfvars -input=false
          terraform show -no-color tfplan.binary > tfplan.txt
      - name: checkov plan scan
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/checkov-plan-scan
        with:
          tf_directory: eks
          checkov_soft_fail: ${{ env.CHECKOV_SOFT_FAIL }}
      - name: comment plan on pr
        if: github.event_name == 'pull_request'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('eks/tfplan.txt', 'utf8');
            const commentBody = `### Terraform Plan for EKS\n\`\`\`\n${plan}\n\`\`\``;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,  
              repo: context.repo.repo,
              body: commentBody
            });
      - name: Terraform Apply
        if: github.event_name == 'push' 
        working-directory: eks
        run: terraform apply -auto-approve tfplan.binary
  
  rds:
    needs: [detect-which-dirs-changed, vpc]
    environment: dev
    if: always() && needs.detect-which-dirs-changed.outputs.rds == 'true' && (needs.vpc.result == 'success' || needs.vpc.result == 'skipped')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: set up Terraform, cache providers, and configure AWS credentials
        uses: ./.github/workflows/terraform-aws-init
        with:
          tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }}
          terraform_version: 1.15.8
          aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
          aws_region: us-east-1
          backend_bucket: ${{ vars.BACKEND_BUCKET }}
          backend_key: ${{ vars.RDS_BACKEND_KEY }}
          working_directory: rds
      - name: Terraform Plan
        working-directory: rds
        shell: bash
        run: |
          terraform plan -out=tfplan.binary -var-file=./environment/dev.tfvars -var="db_username=${{ secrets.DB_USERNAME }}" -input=false
          terraform show -no-color tfplan.binary > tfplan.txt
      - name: checkov plan scan
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/checkov-plan-scan
        with:
          tf_directory: rds
          checkov_soft_fail: ${{ env.CHECKOV_SOFT_FAIL }}
      - name: comment plan on pr
        if: github.event_name == 'pull_request'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('rds/tfplan.txt', 'utf8');
            const commentBody = `### Terraform Plan for RDS\n\`\`\`\n${plan}\n\`\`\``;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
      - name: Terraform Apply
        if: github.event_name == 'push' 
        working-directory: rds
        run: terraform apply -auto-approve tfplan.binary

  addons:
    needs: [detect-which-dirs-changed, eks, vpc]
    environment: dev
    if: always() && needs.detect-which-dirs-changed.outputs.addons == 'true' && (needs.eks.result == 'success' || needs.eks.result == 'skipped') && (needs.vpc.result == 'success' || needs.vpc.result == 'skipped')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: set up Terraform, cache providers, and configure AWS credentials
        uses: ./.github/workflows/terraform-aws-init
        with:
          tf_plugin_cache_dir: ${{ env.TF_PLUGIN_CACHE_DIR }}
          terraform_version: 1.15.8
          aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
          aws_region: us-east-1
          backend_bucket: ${{ vars.BACKEND_BUCKET }}
          backend_key: ${{ vars.ADDONS_BACKEND_KEY }}
          working_directory: addons
      - name: Terraform Plan
        working-directory: addons
        run: |
            terraform plan -out=tfplan.binary -var-file=./environment/dev.tfvars -input=false
            terraform show -no-color tfplan.binary > tfplan.txt
      - name: checkov plan scan
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/checkov-plan-scan
        with:
          tf_directory: addons
          checkov_soft_fail: ${{ env.CHECKOV_SOFT_FAIL }}
      - name: comment plan on pr
        if: github.event_name == 'pull_request'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('addons/tfplan.txt', 'utf8');
            const commentBody = `### Terraform Plan for Addons\n\`\`\`\n${plan}\n\`\`\``;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: addons
        run: terraform apply -auto-approve tfplan.binary  